version: '3'
services:
  database-mongo:
    container_name: orders-service-db
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - tech-challenge

volumes:
  mongo_data: {}

networks:
  tech-challenge:
    driver: bridge
