version: '3'
services:
  database-mongo:
    container_name: orders-service-db
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - tech-challenge

  localstack:
    container_name: local-aws-services
    image: localstack/localstack:latest
    environment:
      - SERVICES=sns
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "./.localstack:/var/lib/localstack"

volumes:
  mongo_data: {}

networks:
  tech-challenge:
    driver: bridge
